lotr:
    resource: "@LotrBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: {_format: json}

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@LotrBundle/Controller/AdminController.php"
    type:     annotation
    defaults: {_format: html}

# Places
get_places:
    pattern:  /places.{_format}
    defaults: { _controller: LotrBundle:Places:getPlaces, _format: json }

get_place:
    pattern:  /place/{slug}.{_format}
    defaults: { _controller: LotrBundle:Places:getPlace, _format: json }

get_place_all_characters:
    pattern:  /place/{slug}/characters.{_format}
    defaults: { _controller: LotrBundle:Places:getPlaceAllCharacters, _format: json }

get_place_all_characters_by_date:
    pattern:  /place/{slug}/characters/date/{date}.{_format}
    defaults: { _controller: LotrBundle:Places:getPlaceAllCharactersByDate, _format: json }

get_place_all_characters_by_period:
    pattern:  /place/{slug}/characters/period/{date1}/{date2}.{_format}
    defaults: { _controller: LotrBundle:Places:getPlaceAllCharactersByPeriod, _format: json }

# Events
get_events:
    pattern: /events.{_format}
    defaults: { _controller: LotrBundle:Events:getEvents, _format: json }

get_event:
    pattern: /event/{slug}.{_format}
    defaults: { _controller: LotrBundle:Events:getEvent, _format: json }

get_event_position_characters:
    pattern: /event/{slug}/position/characters.{_format}
    defaults: { _controller: LotrBundle:Events:getEventPositionCharacters, _format: json }

get_event_present_characters:
    pattern: /event/{slug}/present/characters.{_format}
    defaults: { _controller: LotrBundle:Events:getEventPresentCharacters, _format: json }