lotr:
    resource: "@LotrBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: {_format: json}

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@LotrBundle/Controller/AdminController.php"
    type:     annotation
    defaults: {_format: html}