lotr:
    resource: "@LotrBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Character Alone
get_character:
    pattern:  /character/{slug}.{_format}
    defaults: { _controller: LotrBundle:Characters:getCharacter, _format: json }

get_character_by_date:
    pattern:  /character/{slug}/date/{date}.{_format}
    defaults: { _controller: LotrBundle:Characters:getCharacterTripByDate, _format: json }

get_character_by_place:
    pattern:  /character/{slug}/place/{place}.{_format}
    defaults: { _controller: LotrBundle:Characters:getCharacterTripByPlace, _format: json }

get_character_by_place_and_place:
    pattern:  /character/{slug}/place/{place}/date/{date}.{_format}
    defaults: { _controller: LotrBundle:Characters:getCharacterTripByPlaceAndDate, _format: json }

# Multi Charater
get_characters:
    pattern:  /characters.{_format}
    defaults: { _controller: LotrBundle:Characters:getCharacters, _format: json }

# Places
get_places:
    pattern:  /places.{_format}
    defaults: { _controller: LotrBundle:Places:getPlaces, _format: json }

get_place:
    pattern:  /place/{slug}.{_format}
    defaults: { _controller: LotrBundle:Places:getPlace, _format: json }

get_place_all_characters:
    pattern:  /place/{slug}/characters.{_format}
    defaults: { _controller: LotrBundle:Places:getPlaceAllCharacters, _format: json }

get_place_all_characters_by_date:
    pattern:  /place/{slug}/characters/date/{date}.{_format}
    defaults: { _controller: LotrBundle:Places:getPlaceAllCharactersByDate, _format: json }