lotr:
    resource: "@LotrBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: {_format: json}

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@LotrBundle/Controller/AdminController.php"
    type:     annotation
    defaults: {_format: html}

# Events
#get_events:
#    pattern: /events.{_format}
#    defaults: { _controller: LotrBundle:Events:getEvents, _format: json }

#get_event:
#    pattern: /event/{slug}.{_format}
#    defaults: { _controller: LotrBundle:Events:getEvent, _format: json }

#get_event_position_characters:
#    pattern: /event/{slug}/position/characters.{_format}
#    defaults: { _controller: LotrBundle:Events:getEventPositionCharacters, _format: json }

#get_event_present_characters:
#    pattern: /event/{slug}/present/characters.{_format}
#    defaults: { _controller: LotrBundle:Events:getEventPresentCharacters, _format: json }