lotr:
    resource: "@LotrBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Character Alone
get_character:
    pattern:  /character/{slug}.{_format}
    defaults: { _controller: LotrBundle:Characters:getCharacter, _format: json }

get_character_by_date:
    pattern:  /character/{slug}/date/{date}.{_format}
    defaults: { _controller: LotrBundle:Characters:getCharacterTripByDate, _format: json }

# Multi Charater
get_characters:
    pattern:  /characters.{_format}
    defaults: { _controller: LotrBundle:Characters:getCharacters, _format: json }

# Places
get_places:
    pattern:  /places.{_format}
    defaults: { _controller: LotrBundle:Places:getPlaces, _format: json }