# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    event_to_date:
        class: LotrBundle\Service\eventToDate
        arguments: ["$unknown", doctrine.orm.entity_manager]