<?php

namespace LotrBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CharactersTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactersTripRepository extends EntityRepository
{
    public function getCharactersTripByDate($slug, $date)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.date = :date AND c.character = :slug')
            ->setParameter('date', $date)
            ->setParameter('slug', $slug)
            ->getQuery();

        $result = $query->getResult();

        if(!$result)
        {
            $result = "error : date not found";
        }

        return $result;
    }
}
